name: Publish GitHub Pages

on:
  push:
    branches: ["publish"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build with Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - uses: actions/upload-pages-artifact@v2
        with:
          path: dist/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
